### ISSUE TITLE
Feature request: Show timestamp of when a poll closed

### ISSUE THREAD

**Issue by RichiH** [andrewcmyers/civs#10]
As per subject and our emails.

**Comment by andrewcmyers** [comment]
The results page for a poll already shows when the poll closed.

**Comment by RichiH** [comment]
The admin interface, however, does not.

**Comment by andrewcmyers** [comment]
Good point, that should be fixed.

**Comment by andrewcmyers** [comment]
This has been fixed.

**Comment by RichiH** [comment]
Thanks!
