### ISSUE TITLE
minimax

### ISSUE THREAD

**Issue by andrewcmyers** [andrewcmyers/civs#12]
CIVS should really support the minimax completion algorithm. It's even cheaper than Schulze, easy to implement, and satisfies criteria that other algorithms don't.

**Comment by luiscastro193** [comment]
Which criteria? Does it have something to do with burying attacks? Because I am concerned about that but Condorcet-IRV seems too extreme.

**Comment by luiscastro193** [comment]
After some investigation it doesn´t seems like it does. Sticking to Condorcet-IRV then.

**Comment by andrewcmyers** [comment]
Minimax satisfies the criterion that it chooses the candidate who needs the fewest ballots changed to become the Condorcet winner.

Actually I have by now implemented minimax.
