### ISSUE TITLE
[Bug] Proportional representation not reading votes properly

### ISSUE THREAD

**Issue by luiscastro193** [andrewcmyers/civs#16]
I created a test poll with 4 options and "Enforce proportional representation" activated (2 choices would win).

The file uploaded contained these votes:
1, 4, 3, 2
4, 1, 3, 2

However, in the "Nonproportional poll" section the third choice won over the fourth.

These are the poll results: http://civs.cs.cornell.edu/cgi-bin/results.pl?num_winners=2&id=E_c8886312c2f0969f

You can see the actual votes downloading the CSV.

**Comment by luiscastro193** [comment]
This is interesting... If you vote manually, the ballots are counted right but now the CSV is wrong. Again, it exchanges the positions of the third and fourth options.

Proof: http://civs.cs.cornell.edu/cgi-bin/results.pl?id=E_ba7cef011124f5bb

**Comment by andrewcmyers** [comment]
There is a bit of a hack in the way proportional mode works, in that rankings are inverted.

**Comment by luiscastro193** [comment]
Oh now I get it. Thanks a lot!
