### ISSUE TITLE
Redundant invites

### ISSUE THREAD

**Issue by andrewcmyers** [andrewcmyers/civs#48]
If someone is invited more than once to a poll before they opt in, they get a list of redundant invitations when they do opt in. Not a big issue, since they can't actually vote more than once.

**Comment by andrewcmyers** [comment]
fixed.

**Comment by masiarek** [comment]
Sent from a mobile device. ***@***.***; phone 919-602-5424

Address:
422 Halls Mill Drive
Cary, NC 27519
