### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by ljharb** [andrewcmyers/civs#53]
http://civs.cs.cornell.edu/ and https://civs.cs.cornell.edu/ both fail to load.

**Comment by andrewcmyers** [comment]
There has been a hardware failure but the system will be back up soon.

**Comment by andrewcmyers** [comment]
The system is partly back up, but new polls cannot be started until some new DNS entries happen.

**Comment by andrewcmyers** [comment]
The website is back up again and should be working correctly. Thanks for reporting.

**Comment by ljharb** [comment]
Thank you!
