### ISSUE TITLE
The voter's key will be resent to the voter. Sending mail to voter "xxxx"... EndMailData: [Net::SMTP] Timeout

### ISSUE THREAD

**Issue by aanm** [andrewcmyers/civs#55]
Hey @andrewcmyers ,

I'm currently facing an issue with civs on a private poll. It seems that not all voters are able to see the poll after I added them. The error SMTP error from the title seems to be related to the voters that can't see the poll

```
Voter <A> is already authorized. The voter's key will be resent to the voter. Sending mail to voter "A"... EndMailData: [Net::SMTP] Timeout 
Voter <B> is already authorized. The voter's key will be resent to the voter. 
Voter <C> is already authorized. The voter's key will be resent to the voter. Sending mail to voter "C"... EndMailData: [Net::SMTP] Timeout
Skipping voter <D>: already voted.
```
Both voters B and D can see the poll but voters A and C can't.

**Comment by andrewcmyers** [comment]
Sounds like the system was not able to send them email. You can resend to them safely and it should work assuming their email systems are back up.

**Comment by aanm** [comment]
Hi again @andrewcmyers, thank you very much for the reply. I think I was able to pin point the problem which perhaps might be a bug. I've noticed that all voters that are getting a "EndMailData: [Net::SMTP] Timeout" are voters that already voted on a previous private poll. This is reproducible, the voters that get the SMTP error every time are the same ones that voted on a previous private poll.

**Comment by andrewcmyers** [comment]
Are you able to email these voters directly yourself? It sounds like their email system is refusing mail from the system.

**Comment by aanm** [comment]
I thought since April 2021 CIVS didn't send any email and instead had opt-in system. Are you saying that for users that opt-in CIVS system can't reach them?

For my particular issue, all voters share the same domain name, and they are all part of a Google Workspace.

I for once can't vote on a private poll that I created myself because one of those voters emails is mine.

**Comment by andrewcmyers** [comment]
CIVS still sends voter keys by email, but only to voters who have opted in. It sounds like the email addresses given for the voters are not working. When a voter who has not opted in is invited to vote, the system records it as a pending invitation that is shown when the voter does opt in. But once they have opted in, it expects to be able to email them the invitation.

**Comment by andrewcmyers** [comment]
I can poke at this from my end if you send me your email that does not work (maybe not by posting on Github though)

**Comment by aanm** [comment]
> I can poke at this from my end if you send me your email that does not work (maybe not by posting on Github though)

I've just sent you an e-mail with more information.

**Comment by gmagyarf** [comment]
Very curiously the same timeout message is appearing for some of our voters registering in CIVS for the first time. The emails are a varied bunch, and it seems that the location of the submitters was more important. Opting-in from South America (ARG, URU, BRA) gave them this timeout with any email (gmail, outlook as well). The same email would start the opt-in procedure from Europe. Very strange.

**Comment by andrewcmyers** [comment]
Do the voters have any non-ASCII characters in their name or email address? (This should work but it's a potential source of problems)

**Comment by andrewcmyers** [comment]
Also, the name/address of the supervisor might be relevant. You can email me that info.

**Comment by gmagyarf** [comment]
I would not think that they do. Will email details.

**Comment by andrewcmyers** [comment]
Fixed. The problem was that the "From" email address was getting split across multiple encoding segments when the user's language used non-ASCII characters; apparently, many SMTP servers don't like that, although the relevant specs seem to allow it.
